### ISSUE TITLE
Support adding an XML Declaration

### ISSUE THREAD

**Issue by Haroenv** [steelbrain/jsx-string#6]
Just creating the string with `<?xml version="1.0" encoding="utf-8"?>` in front of it, or maybe something with `{encoding: 'utf-8', declaration: true}` as an option

**Comment by steelbrain** [comment]
Hi @Haroenv 

This is actually disallowed by the JSX Syntax. You can put this part in a string and the rest in JSX and it'll look like
```
function getXMLContent(content) {
  return `<?xml version="1.0" encoding="utf-8"?>${jsxString(content)}`
}
```
and then you can do
```
getXMLContent(
  <a>Hello</a>
)
```

**Comment by Haroenv** [comment]
Makes sense, totally valid to keep this out of scope.
